@startuml
skinparam componentStyle rectangle
actor user
file file
component {
    user -d-> [UI]
    [Main] -up-> [UI]
    [Main] -d-> [Storage]
    [UI] -> [Parser]
    [Parser] -> [Command]
    [Command] -> [Main]
    [Command] <-> [StateManager]
    [Storage] <-> [StateManager]
    [Storage] -l-> file
}
@enduml