@startuml
mainframe **sd** export expense data
-> ":ExportCommand": exportExpenseData()
activate ":ExportCommand" #FFBBBB
loop for every Income in incomeArray
    ":ExportCommand" -> ":Income": getTransaction()
    activate ":Income" #FFBBBB
    ":Income" --> ":ExportCommand": currentTransaction: Transaction
    deactivate
    create ":String[]"
    ":ExportCommand" -> ":String[]": new String[DATA_LENGTH]
    activate ":String[]" #FFBBBB
    ":String[]" --> ":ExportCommand": row: String[]
    deactivate
    ":ExportCommand" -> ":Income": getCategory()
    activate ":Income" #FFBBBB
    ":Income" --> ":ExportCommand": category: Category
    deactivate
    ":ExportCommand" -> ":Category": getName()
    activate ":Category" #FFBBBB
    ":Category" --> ":ExportCommand": row[CATEGORY]: String
    deactivate
    ":ExportCommand" -> ":ExportCommand": extractTransactionData(currentTransaction, row)
    activate ":ExportCommand" #FFBBBB
    ref over ":ExportCommand": extract transaction data
    ":ExportCommand" --> ":ExportCommand": row: String[]
    deactivate
    ":ExportCommand" -> "csvFile:CsvWriter": write(row)
    activate "csvFile:CsvWriter" #FFBBBB
    "csvFile:CsvWriter" --> ":ExportCommand"
    deactivate
end
<-- ":ExportCommand"
deactivate
@enduml